<a href="https://colab.research.google.com/github/tesygithub/Machine-Learning/blob/main/Spam_Mail_Prediction(Logistic_Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Spam Mail Prediction

**Import Dependancy**

In [2]:
# Import Dependancy
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
df = pd.read_csv('/content/Copy of mail_data.csv')

In [4]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.shape

(5572, 2)

### Dealing with null values

**Replacing null values with null string**

In [7]:
df.isnull().sum()


Category    0
Message     0
dtype: int64

### Lable Encoding

*   ham	converted as 1
*   spam converted as 0



In [8]:
# Lable Encoding
df.loc[df['Category'] == 'spam', 'Category',] = 0
df.loc[df['Category'] == 'ham', 'Category',] = 1
df.head()

Category                                            Message
0        1  Go until jurong point, crazy.. Available only ...
1        1                      Ok lar... Joking wif u oni...
2        0  Free entry in 2 a wkly comp to win FA Cup fina...
3        1  U dun say so early hor... U c already then say...
4        1  Nah I don't think he goes to usf, he lives aro...

### Train Test Split

**Sepret data as x and y**

In [9]:
x = df['Message']
y = df['Category']

**Spliting the data as train data and test data**

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=3)

### Feature Extraction

**convert text data into numerical data**

In [11]:
x_train.head()

3075                  Don know. I did't msg him recently.
1787    Do you know why god created gap between your f...
1614                         Thnx dude. u guys out 2nite?
4304                                      Yup i'm free...
3266    44 7732584351, Do you want a New Nokia 3510i c...
Name: Message, dtype: object

In [12]:
x_test.head()

2632    URGENT! Your mobile No 077xxx WON a £2,000 Bon...
454     Ok i will tell her to stay out. Yeah its been ...
983     Congrats! 2 mobile 3G Videophones R yours. cal...
1282        Am I the only one who doesn't stalk profiles?
4610                               Y de asking like this.
Name: Message, dtype: object

In [14]:
# convert text data into num data
feature_extraction = TfidfVectorizer(min_df=1, stop_words='english', lowercase=True)

# Fit the data
x_train_features = feature_extraction.fit_transform(x_train)
x_test_features = feature_extraction.transform(x_test)

In [15]:
print(x_train_features[:5])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 41 stored elements and shape (5, 7431)>
  Coords	Values
  (0, 2329)	0.38783870336935383
  (0, 3811)	0.34780165336891333
  (0, 2224)	0.413103377943378
  (0, 4456)	0.4168658090846482
  (0, 5413)	0.6198254967574347
  (1, 3811)	0.17419952275504033
  (1, 3046)	0.2503712792613518
  (1, 1991)	0.33036995955537024
  (1, 2956)	0.33036995955537024
  (1, 2758)	0.3226407885943799
  (1, 1839)	0.2784903590561455
  (1, 918)	0.22871581159877646
  (1, 2746)	0.3398297002864083
  (1, 2957)	0.3398297002864083
  (1, 3325)	0.31610586766078863
  (1, 3185)	0.29694482957694585
  (1, 4080)	0.18880584110891163
  (2, 6601)	0.6056811524587518
  (2, 2404)	0.45287711070606745
  (2, 3156)	0.4107239318312698
  (2, 407)	0.509272536051008
  (3, 7414)	0.8100020912469564
  (3, 2870)	0.5864269879324768
  (4, 2870)	0.41872147309323743
  (4, 487)	0.2899118421746198
  (4, 621)	0.2899118421746198
  (4, 7090)	0.1468655885827845
  (4, 4582)	0.15712819632394748
  (4, 46

In [16]:
y_train.info()

<class 'pandas.core.series.Series'>
Index: 4457 entries, 3075 to 1688
Series name: Category
Non-Null Count  Dtype 
--------------  ----- 
4457 non-null   object
dtypes: object(1)
memory usage: 69.6+ KB


In [17]:
y_train = y_train.astype('int')
y_test = y_test.astype('int')

In [18]:
y_train.info()

<class 'pandas.core.series.Series'>
Index: 4457 entries, 3075 to 1688
Series name: Category
Non-Null Count  Dtype
--------------  -----
4457 non-null   int64
dtypes: int64(1)
memory usage: 69.6 KB


### Create model

**Logistic regression**

In [19]:
model = LogisticRegression()
model.fit(x_train_features, y_train)


LogisticRegression()

### Eveluating the training model

**Prediction score on training data**

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score, precision_score, recall_score

In [21]:
train_pred = model.predict(x_train_features)
test_pred = model.predict(x_test_features)
print("Accuracy score on training data : ", accuracy_score(y_train, train_pred))
print("Precision Score on training data :", precision_score(y_train, train_pred))
print("Recall Score on training data :", recall_score(y_train, train_pred))
print("Confusion Matrix Score on training data :\n", confusion_matrix(y_train, train_pred))
print(' ')
print('*'*80)
print(' ')
print("Accuracy score on test data : ", accuracy_score(y_test, test_pred))
print("Precision Score on test data :", precision_score(y_test, test_pred))
print("Recall Score on test data :", recall_score(y_test, test_pred))
print("Confusion Matrix Score on test data :\n", confusion_matrix(y_test, test_pred))

Accuracy score on training data :  0.9676912721561588
Precision Score on training data : 0.9650087478130467
Recall Score on training data : 0.9989650711513584
Confusion Matrix Score on training data :
 [[ 452  140]
 [   4 3861]]
 
********************************************************************************
 
Accuracy score on test data :  0.9668161434977578
Precision Score on test data : 0.9628886659979939
Recall Score on test data : 1.0
Confusion Matrix Score on test data :
 [[118  37]
 [  0 960]]


**Random Forest**

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
model = RandomForestClassifier()
model.fit(x_train_features, y_train)

RandomForestClassifier()

### Eveluating the training model

**Prediction score on training data**

In [25]:
train_pred = model.predict(x_train_features)
test_pred = model.predict(x_test_features)
print("Accuracy score on training data : ", accuracy_score(y_train, train_pred))
print("Precision Score on training data :", precision_score(y_train, train_pred))
print("Recall Score on training data :", recall_score(y_train, train_pred))
print("Confusion Matrix Score on training data :\n", confusion_matrix(y_train, train_pred))
print(' ')
print('*'*80)
print(' ')
print("Accuracy score on test data : ", accuracy_score(y_test, test_pred))
print("Precision Score on test data :", precision_score(y_test, test_pred))
print("Recall Score on test data :", recall_score(y_test, test_pred))
print("Confusion Matrix Score on test data :\n", confusion_matrix(y_test, test_pred))

Accuracy score on training data :  1.0
Precision Score on training data : 1.0
Recall Score on training data : 1.0
Confusion Matrix Score on training data :
 [[ 592    0]
 [   0 3865]]
 
********************************************************************************
 
Accuracy score on test data :  0.9748878923766816
Precision Score on test data : 0.97165991902834
Recall Score on test data : 1.0
Confusion Matrix Score on test data :
 [[127  28]
 [  0 960]]


### Building a Predictive System

In [26]:
input_data = ["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"]

input_data_feature = feature_extraction.transform(input_data)

prediction = model.predict(input_data_feature)
print(prediction)

if prediction[0] == 1:
  print('Ham mail')
else:
  print('Spam mail')

[0]
Spam mail


In [27]:
# loading library
import pickle

In [28]:
with open('spaim_mail_pred', 'wb') as files:
    pickle.dump(model, files)